#--------------------------------------------------
# Default Application Settings (geared for local)
#--------------------------------------------------
logging.level:
  root: INFO
  com.onlineinteract: INFO

application:
  name: kafka-topic-monitor
  version: 0.0.1
  env-code: l  
  audit.enabled: false
  
server:
  contextPath: /
  port: 8091
  
authentication:
  username: test
  password: password
  
kafka:
  bootstrap.servers: colossal.canadacentral.cloudapp.azure.com:29092
  schema.registry.url: http://colossal.canadacentral.cloudapp.azure.com:8081
  